### ISSUE TITLE
CSS Inline coloring missing

### ISSUE THREAD

**Issue by basarat** [Microsoft/monaco-css#2]
Looking at the sample : https://microsoft.github.io/monaco-editor/index.html css no longer has the nice color inline widget that it used to :rose: 

![image](https://cloud.githubusercontent.com/assets/874898/16371330/548fb46e-3c89-11e6-9461-7de5f3a075e7.png)

refs https://github.com/Microsoft/vscode/issues/8172

**Comment by alexandrudima** [comment]
We had to take it out briefly to not get blocked by this, but we plan to bring it back ASAP

**Comment by jrieken** [comment]
This issue was moved to Microsoft/monaco-editor#132
