### ISSUE TITLE
Doesn't have a token provider 

### ISSUE THREAD

**Issue by basarat** [Microsoft/monaco-css#4]
The setup mode doesn't come with a token provider so there isn't any syntax highlighting. I see that its not mentioned as a provided feature in the readme either so will it be implemented? :-/ 

Should be registered here : https://github.com/Microsoft/monaco-css/blob/a95094a5990b443cead16f31c374a3c8c2966bfe/src/cssMode.ts#L29-L36 :rose:

refs https://github.com/Microsoft/monaco-css/issues/3 https://github.com/alm-tools/alm/issues/138 https://github.com/alm-tools/alm/pull/139

**Comment by alexandrudima** [comment]
* monaco-languages supplies basic coloring support for css, less and sass
* this repo provides advanced language features for those languages

**Comment by aeschli** [comment]
Yes, as Alex says. But if you guys prefer I can move it. For JSON I kept it in the monaco-json repo.
